name: バグ報告
description: 不具合報告はこちら
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |- 
        不具合の概要を記載してください。
        見た目に関係する場合は、スクリーンショット等を貼り付けてください。
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: 再現環境
      description: |-
        再現環境を記載してください。
        (バージョンまであった方が親切だが、バージョン非依存な不具合も多いため手間な場合は省略可)
        例)
        Chrome + Windows
        Edge + Windows
        Chrome + macOS
        Safari + macOS
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |-
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足
