name: 改善
description: 改善系はこちら
body:
  - type: textarea
    id: contact
    attributes:
      label: 背景
      description: どのような課題を抱えてissueを立てたのか、経緯や前提を記載してください。
    validations:
      required: false
  - type: textarea
    id: merit
    attributes:
      label: メリット
      description: 改善することでどのようなメリットがあるのかを記載してください。
    validations:
      required: false
  - type: textarea
    id: toDo
    attributes:
      label: やること
      description: このissueで取り組むことを記載してください。
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足